#!/bin/bash

# OK so now we have the two file lists (generated by `compare_folders.sh`) which are basically like two small DB's (or perhaps two tables).
# Now we need to write the logic that compares the two lists
#
# What we want to know is:
# 1. Which files exist in the source but not in the dest dir (and vice versa)
# 2. Which files exist in both dirs but have different sizes
#
# I guess that's it
#
# What we need to decide is what is considered the same file
# -> same name is not an option because we might have two different files with the same name
# -> same folder+name might be an option, but we need to assume that the parent dirs have the same name

if [[ $# != 2 ]]; then
	echo "usage: $0 <source file list> <dest file list>"
	echo
	echo "the script uses two file lists generated by 'compare_folders.sh' to figure out which files are different or missing"
	exit 1
fi

# Hmmm actually maybe it will be easier to write this part in python..
